spring:
  profiles:
    active: dev

logging:
  level:
    com:
      example: debug


management:
  endpoints:
    web:
      exposure:
        include: health,metrics,refresh


app:
  property1: "property1 data"
  property2: "property2 data"
  schedulers:
    scheduler1:
      id: scheduler1
      interval: 5000
      time-unit: milliseconds
      enabled: true
    scheduler2:
      id: scheduler2
      interval: 5000
      time-unit: milliseconds
      enabled: true